### PR TITLE
update LU scraper to use different csv files as historized sources

### LINKED ISSUE #1358: LU scraping URL changed
currently: [https://www.lustat.ch/analysen/gesundheit/corona-reporting](https://www.lustat.ch/analysen/gesundheit/corona-reporting)
with different page layout

### PR DESCRIPTION
**Pull request by maekke**
could fix #1358 if it actually works...

### CODE REVIEW

**Comment by metaodi** [comment]
I'm using this PR as a starting point, I don't think we get better data any time soon.

**Comment by maekke** [comment]
@metaodi I added scraping of isolated, quarantined and travel quarantined in f2b0e63 and removed the old logic. I guess that should be all, what's needed?

**Comment by metaodi** [comment]
@maekke you mentioned something about the dates not matching or being off by one (can't remember exactly). That's why I wanted to check if the out put somewhat matches with what we have in the repo.

But yes I agree, that's all!

**Comment by maekke** [comment]
> @maekke you mentioned something about the dates not matching or being off by one (can't remember exactly). That's why I wanted to check if the out put somewhat matches with what we have in the repo.
> 
> But yes I agree, that's all!

Ah I see, the month "off by one" is taken care of in `fix_lu_date`. So from my side it should be fine as well!

**Comment by metaodi** [comment]
> > @maekke you mentioned something about the dates not matching or being off by one (can't remember exactly). That's why I wanted to check if the out put somewhat matches with what we have in the repo.
> > But yes I agree, that's all!
> 
> Ah I see, the month "off by one" is taken care of in `fix_lu_date`. So from my side it should be fine as well!

btw: in the meantime I figured out why the month is off by one: these CSVs are used to display tHe Highcharts charts using JavaScript. And in JavaScript the months actually start at 0, i.e. in JS `Date.UTC(2020, 10, 12)` is equal to 2020-11-12.

**Pull request merged**
