### PR TITLE
Split response by article in scrape_ag.sh

### LINKED ISSUE #297: AG scraper with wrong date
Today the scraper added a new entry with the same numbers as yesterday. When checking [the website](https://www.ag.ch/de/themen_1/coronavirus_2/alle_ereignisse/alle_ereignisse_1.jsp), these numbers were not there.

But the scraper code extracts the first entry in the timeline and then proceeds to get the first numbers on the page (in this case from yesterday). So they were erroneously assigned with todays date.

### PR DESCRIPTION
**Pull request by fabian**
Fixes #297

### CODE REVIEW

**Comment by baryluk** [comment]
Does this fixes it actually? I still get wrong output.

Also,

```python3
d = "\n".join(l for l in d.split('<article'))
```

is equivalent to:

```python3
d = "\n".join(d.split('<article'))
```

**Comment by fabian** [comment]
@baryluk Thanks for the code tip! ☺️ 

Hmm yes works for me as it runs now only on articles starting with "Neues Lagebulletin" (the first one). Note that the "Date and time" is now correct 27.03.2020:

```
$ scrapers/scrape_ag.sh
AG
Downloading: https://www.ag.ch/de/themen_1/coronavirus_2/alle_ereignisse/alle_ereignisse_1.jsp
Scraped at: 2020-03-28T22:19:16+01:00
Date and time: 2020-03-27T15:00:00
Confirmed cases: 364
Hospitalized: 50
ICU: 12
Vent: 9
Deaths: 3
```

**Comment by baryluk** [comment]
Vent, should be 10. Not 9.

Maybe use this:

```python3
print('Vent:', sc.find(r'\b([0-9]+)\s*Person(en)? k(ü|&uuml;)nstlich beatmet werden', d))
```

Similar modification could be made to ICU probably.

I didn't test it.

**Comment by fabian** [comment]
Ah yes, didn't notice Vent was wrong - fixed:

```
$ scrapers/scrape_ag.sh
AG
Downloading: https://www.ag.ch/de/themen_1/coronavirus_2/alle_ereignisse/alle_ereignisse_1.jsp
Scraped at: 2020-03-28T22:28:22+01:00
Date and time: 2020-03-27T15:00:00
Confirmed cases: 364
Hospitalized: 50
ICU: 12
Vent: 10
Deaths: 3
```

**Pull request merged**
