### PR TITLE
Adapts the BL scrapper to the new webpage for BL

### PR DESCRIPTION
**Pull request by deragent**
Starting from tomorrow, BL data is only published under: https://www.baselland.ch/politik-und-behorden/direktionen/volkswirtschafts-und-gesundheitsdirektion/amt-fur-gesundheit/medizinische-dienste/kantonsarztlicher-dienst/aktuelles/covid-19-faelle-kanton-basel-landschaft

This web page embeds the following graph: https://www.statistik.bl.ch/files/sites/Grafiken/COVID19/Grafik_COVID19_BL_Linie.htm

The data is in the HTML within a

    <pre id="data" >
    ....
    </pre>

block.

This pull request updates the scraper_bl.sh to pull the data from there.

### CODE REVIEW

**Comment by deragent** [comment]
#149

**Comment by baryluk** [comment]
Thanks for the fix. Nice!

Other than a comment on the curl thing, ack from me.

**Comment by deragent** [comment]
I updated the download to not use curl directly.
Also removed a marge conflict with the current master, so could be merged now.

**Comment by baryluk** [comment]
Looks good. Thank you!

**Pull request merged**
