### PR TITLE
Use proper number for confirmed cases in BS scraper. Prepare regexp f…

### PR DESCRIPTION
**Pull request by baryluk**
…or extracting more numbers.

Closes: https://github.com/openZH/covid_19/issues/193

### CODE REVIEW

**Comment by metaodi** [comment]
Please rebase to fix the validation errors.

**Comment by baryluk** [comment]
> Please rebase to fix the validation errors.

The PR doesn't touch CSV files. You can just ignore the errors.

**Comment by metaodi** [comment]
Force doesn't work since in your branch the errors are still there (that's why I asked for a rebase).

And yes sure I can ignore them, but GitHub doesn't allow merging PRs with failed checks from mobile. So I'll just do it later/tomorrow then.

**Comment by baryluk** [comment]
On which branch the github actions / checks working on? Directly on my branch, or a temporary local branch with master and merged branch? It shouldn't matter that I have errors on my branch.

**Comment by metaodi** [comment]
The checks run on your branch afaik. But this could be an issue with our validation workflow. I think I will change it, so that the CSV validation only runs on PRs containing CSVs. Sorry about the hassle.

**Pull request merged**
