### PR TITLE
Add scrapers for AR, OW, SO, ZG

### PR DESCRIPTION
**Pull request by baryluk**
Update TODO and STATUS.

Add a new date format to the parser.
And start accepting "Recovered:" field (not used for anything yet).

Closes: https://github.com/openZH/covid_19/issues/112

### CODE REVIEW

**Comment by tlorusso** [comment]
Thx @baryluk! Really valuable & great work.

**Comment by zdavatz** [comment]
so these are still failing

```
UR - - - FAILED
VD - - - FAILED
SZ - - - FAILED
```
and 
`XX - - - FAILED` where @baryluk has his castle I guess ;).

**Comment by baryluk** [comment]
@zdavatz 

UR is handled in https://github.com/openZH/covid_19/pull/116

VD works for me just fine.

SZ is known to be broken. Their website is not providing any new info since 15. March.

Open an issue or anything that is broken.

Cheers.

**Comment by zdavatz** [comment]
ok, see: #120

**Pull request merged**
