### PR TITLE
update TG based on direct email from Kanton Thurgau Staatskanzlei 

### PR DESCRIPTION
**Pull request by zukunft**

### CODE REVIEW

**Comment by zukunft** [comment]
merged version of  #263

**Comment by zukunft** [comment]
Should I solve the merge conflict?

**Comment by jb3-2** [comment]
@zukunft I have resolved the merge conflict. Let's see if we can get this data into master.

**Comment by jb3-2** [comment]
@tlorusso Please merge if you agree.

**Comment by zukunft** [comment]
The data has not been published on the web, I just got an email.

**Comment by zukunft** [comment]
Merci

**Pull request merged**
