### PR TITLE
update NW, because scraper if off?

### PR DESCRIPTION
**Pull request by zukunft**

### CODE REVIEW

**Comment by baryluk** [comment]
Scraper works:

```
./scrape_nw.sh 
NW
Scraped at: 2020-03-23T21:12:10+01:00
Date and time: 23.&nbsp;März 2020, 19.00 Uhr
Confirmed cases: 39
```

Data is also here in the latest scrape: https://www.functor.xyz/covid_19/scrapers/outputs/2020-03-23T21%3A05%2B01%3A00.txt

**Comment by zukunft** [comment]
When are the results of the scraper merged?

**Comment by zdavatz** [comment]
they are not merged I guess. They have to be collected with a Github-Action. @tlorusso?

**Comment by tlorusso** [comment]
@metaodi has automaized some scrapers via github actions today, he's on it to integrate @baryuk s also.

**Pull request merged**
