### PR TITLE
Add isolated and quarantined to parser for AG

### LINKED ISSUE #772: Scrape 'current_isolated' and 'current_quarantined' of Canton AG
With regard to #771, we aim to integrate the respective values from AG's official source file (PDF): https://www.ag.ch/media/kanton_aargau/themen_1/coronavirus_1/lagebulletins/200525_KFS_Coronavirus_Lagebulletin_59.pdf (example)

The values are located below the title "1. Aktuelle Lage im Kanton Aargau" in the second paragraph; atm the respective phrase reads: "Gegenwärtig betreut sind 33 infizierte Personen und 91 enge Kontaktpersonen."

"33 [infizierte Personen]" corresponds to the value of the variable 'current_isolated'
"91 [enge Kontaktpersonen]" corresponds to the value of the variable 'current_quarantined'

### PR DESCRIPTION
**Pull request by fabian**
This pull request adjusts the scraper AG for the new variables, but further code changes are required in the shared `run_scraper.sh` code to make it work (#771), marked as draft for now.

Closes #772

### CODE REVIEW

**Comment by metaodi** [comment]
@fabian I could take care of the shared code in  parse_scrape_output.py and add_to_db.py if you want.

**Comment by fabian** [comment]
@metaodi That would be great, thanks!

**Comment by fabian** [comment]
Depends on https://github.com/openZH/covid_19/pull/788

**Comment by metaodi** [comment]
Thanks a lot!

**Pull request merged**
