### PR TITLE
Update numbers from AG for 26.03.2020

### PR DESCRIPTION
**Pull request by fabian**
Scrapper worked well, but manually added additional numbers and source PDF link.

Also reduced cron.

### CODE REVIEW

**Comment by andreasamsler** [comment]
Thanks Fabian, checking ..

**Comment by andreasamsler** [comment]
@tlorusso @metaodi  data checked. Is valid. Please resolve conflicts and merge.

**Comment by fabian** [comment]
@andreasamsler Conflict resolved.

**Comment by andreasamsler** [comment]
thanks @fabian

**Pull request merged**
