### PR TITLE
Merge canton csvs

### PR DESCRIPTION
**Pull request by gaberoo**
Hi all,

Here's a small workflow to merge all the cantonal CSVs into a single CSV upon changes to the cantonal CSVs.

I also edited the `validate_csv.sh` workflow to run only when the `csv` files in the main directory are changed.

Filenames etc can be changed. Please review.

### CODE REVIEW

**Comment by zdavatz** [comment]
What should this be good for? Just keep it on your own branch.

**Comment by gaberoo** [comment]
Came as a request from @tlorusso .

**Comment by zdavatz** [comment]
Ok, good to know. Thank you.

**Comment by zdavatz** [comment]
I think this Repo should mainly focus on collecting and validating data, not merging it and creating new lists. That should be done by different projects.

**Comment by gaberoo** [comment]
Here my 2ct: 

I think this came from a motivation to provide data that is maximally useful to a broad community. Sometimes this implies degenerate data storage (like separate and merged forms). Almost any conceivable downstream analysis would be performed on a merged file. However, the separate files create a structure that is easier to maintain.

**Comment by zdavatz** [comment]
We are doing a lot of that stuff here: https://github.com/zdavatz/covid19_ch using the Italian standard as a sample: https://github.com/pcm-dpc/COVID-19/blob/master/README.md

**Pull request merged**
