### PR TITLE
[FIX] fix all scrapers

### PR DESCRIPTION
**Pull request by hroest**
all data scrapers work again (except SZ which didnt publish numbers)

tested on Ubuntu 16.04 with Python 3.6 and 3.8

### CODE REVIEW

**Comment by jb3-2** [comment]
@metaodi @tlorusso It's probably best if one of you reviews this PR, ok?

**Comment by baryluk** [comment]
It looks like I made similar fixes as part of #108 

Also my fixes for VD and TI, made them a bit more robust, and will make sure they work in the future. The URL for VD is dynamic, and must be resolved dynamically, and it is now done as part of #108 

Thanks anyway!

**Comment by zdavatz** [comment]
great!!!

**Comment by metaodi** [comment]
I will merge #108 then.

@hroest if you still have fixes after #108 is merged, please update this PR (or create a new one).

**Comment by metaodi** [comment]
Closing this since the scrapers evolved quite a bit in the meantime. Feel free to open a new PR for further enhancements.

**Pull request closed without merging**
