### PR TITLE
Update COVID19_Fallzahlen_Kanton_NE_total.csv

### PR DESCRIPTION
**Pull request by simgraworldwide**
added historised data, deleted ncumul_vent

### CODE REVIEW

**Comment by baryluk** [comment]
Why values are different than previous ones?

**Comment by baryluk** [comment]
Related to this https://github.com/openZH/covid_19/issues/385 ? I still didn't see an explanation tho.

**Comment by simgraworldwide** [comment]
their numbers changed again with today's update...

**Comment by tlorusso** [comment]
I guess they made a revision? But i can't tell for sure. However, what @simgraworldwide submitted now corresponds to what they report in the new document.

**Pull request merged**
