### PR TITLE
Scrape PDF from NE and extract all numbers

### PR DESCRIPTION
**Pull request by baryluk**
Releated to: https://github.com/openZH/covid_19/issues/357

### CODE REVIEW

**Comment by metaodi** [comment]
Is this stable? I will try test this morning to get a feeling. All these replacements of arbitrary amounts of whitespace seems to break as soon as the PDF changes a bit.

**Comment by baryluk** [comment]
:man_shrugging: 

It did work fine yesterday too. The random amount of whitespaces there are kind of on purpose, because of how `pdftotext -layout` creates a table format.

I should make a bit better comment about it in the source probably.

**Comment by baryluk** [comment]
@maekke97  What do you think?

**Comment by baryluk** [comment]
I added some comments to the scraper, ( https://github.com/openZH/covid_19/blob/f60135e0ed6df5946e2c0b39de9948487489bdf2/scrapers/scrape_ne.py ), that should explain the parsing a bit better.

**Comment by maekke97** [comment]
@baryluk looks good to me except that `d` gets assigned a static string at the moment instead of the one from the pdf. My other comments are rather optional.

**Comment by baryluk** [comment]
@maekke97 Thanks for the review. Addressed the issues.

**Comment by metaodi** [comment]
@baryluk @maekke97 Thank you to both of you!

**Pull request merged**
