### PR TITLE
Fixed scraper for VD

### LINKED ISSUE #133: Scraper for VD failed?
I see data for the 23.03.2020 here https://www.vd.ch/toutes-les-actualites/hotline-et-informations-sur-le-coronavirus/.
... and here https://www.functor.xyz/covid_19/scrapers/outputs/latest.txt I see failed.

### PR DESCRIPTION
**Pull request by dgerber**
Fixes #133.
- Added support for multiple REFRESH "redirects"
- Fixed some sed escapes (for ash shell)

### CODE REVIEW

**Comment by baryluk** [comment]
That is kind of weird, because scrape_vd.sh works for me.

I heard it did fails somehow, but works now, without any changes.

**Comment by dgerber** [comment]
@baryluk yes I guess it's because datawrapper.de only _sometimes_ "redirects" with http-equiv REFRESH more than once. At least once in a browser it sent  me through 3 different pages, /1 -> /14 -> /20 -> /21.

**Comment by baryluk** [comment]
Other than that, ack. It uglifies the scripts quite a bit, but is okish.

Could you also change use of `curl --silent` to instead use `"${DIR}/download.sh"`

?

**Comment by AlexBobAlex** [comment]
Maybe wrong PR for that but what do you thin about using datawrapper api for this one ? It seems more robust. We just need a generated token, the call is as follows : 
```
curl --location --request GET 'https://api.datawrapper.de/v3/charts/tr5bJ/data' --header 'accept: text/csv' --header 'Authorization: Bearer 6868e7b3be4d7a69eff00b1a434ea37af3dac1e76f32d9087fc544dbb3f4e229'
```

And gives back the table straight away :
```
Date	Hospitalisations en cours	Sortis de l'hôpital	Décès	Total cas confirmés
10.03.2020	36	5	1	130
11.03.2020	38	5	2	200
12.03.2020	43	5	3	274
13.03.2020	52	5	2	292
14.03.2020	62	5	3	350
15.03.2020	78	5	4	406
16.03.2020	110	5	5	508
17.03.2020	117	9	5	608
18.03.2020	128	16	5	796
19.03.2020	140	52	7	1212
20.03.2020	152	62	12	1432
21.03.2020	175	70	15	1676
22.03.2020	203	75	16	1782
23.03.2020	223	91	17	2162
24.03.2020	266	100	21	2234
```

**Comment by baryluk** [comment]
@AlexBobAlex Awesome.

Definitively will use this in a new version. I will write it today.

How did you figured this? I tried to search for offical datawrapper API documentation, but couldn't find any on internet.

**Comment by zdavatz** [comment]
welcom @AlexBobAlex good stuff that you are here now too ;) Lets hack!

**Comment by baryluk** [comment]
@AlexBobAlex So, to get a token, one needs to have an account at datawrapper?

**Comment by AlexBobAlex** [comment]
You're welcome. Anything I can do to help.

> How did you figured this?

Before knowing you guys already did scrapers I tried to figure out a way to create ones myself, I started with VD as I live here and curiosity did the rest..

> I tried to search for official datawrapper API documentation, but couldn't find any on internet.

Here it is : https://developer.datawrapper.de/reference

>So, to get a token, one needs to have an account at datawrapper?

Yes, did it yesterday, it's free an tokens don't seem to have a expiry (I should maybe check more in details). You can use mine that I've put in request, no problem with that.

>I will write it today.

Can help as well, on evenings. Just tell me what's best for you or a template I could adapt.

**Comment by dgerber** [comment]
Great, it's certainly cleaner using their API. Hadn't found it either.

**Pull request closed without merging**
