### PR TITLE
Add FR district scraper

### PR DESCRIPTION
**Pull request by maekke**
since FR is only providing the last three weeks, add "incremental" data support to `run_district_scraper.sh ` (not perfect, but it should work). Also note that this will change the order of the file contents between the first and every upcoming run, which shouldn't be a big issue I suppose.

### CODE REVIEW

**Comment by maekke** [comment]
Please wait with merging. The appending of data doesn't work, when data is changed (date/week identical, but for example deceased changes).

**Comment by maekke** [comment]
7d8d082 should fix this issue (hopefully :sweat_smile: ).

**Comment by metaodi** [comment]
@maekke maybe we should use the same mechanism for appending and updating data like the other scraper (using sqlite as an intermediate file format). WDYT?

**Comment by maekke** [comment]
@metaodi this would probably be way better and more robust...

**Comment by metaodi** [comment]
okay, I'll work on that.

**Pull request merged**
